version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: riskmate_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: riskmate_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  csharp-api:
    build:
      context: ./RiskMate.MathEngine
      dockerfile: RiskMate.Api/Dockerfile
    container_name: riskmate_csharp_api
    ports:
      - "5266:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=riskmate_db;Username=postgres;Password=supersecretpassword
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  python-ml:
    build:
      context: ./riskmate-ai-service
      dockerfile: Dockerfile
    container_name: riskmate_python_ml
    ports:
      - "8000:8000"
    volumes:
      - ./riskmate-ai-service/models:/app/models
  frontend:
    build:
      context: ./riskmate-front
      dockerfile: Dockerfile
    container_name: riskmate_frontend
    ports:
      - "3000:80"
    depends_on:
      - python-ml
      - csharp-api

volumes:
  pgdata:
